name: Relase Atlantis Custom Image

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ATLANTIS: "0.22.3"
  TERRAFORM: "1.3.8"
  TERRAGRUNT: "0.38.9"
  TERRAGRUNT_ATLANTIS_CONFIG: "1.16.0"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASE_ENV: staging

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      
      - name: downcase REPO
        run: |
          echo "REPO=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Login to registry ${{ env.REGISTRY_TYPE }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ steps.release.outputs.tag_name }}
          build-args: |
            "ATLANTIS=${{ env.ATLANTIS }}"
            "TERRAFORM=${{ env.TERRAFORM }}"
            "TERRAGRUNT=${{ env.TERRAGRUNT }}"
            "TERRAGRUNT_ATLANTIS_CONFIG=${{ env.TERRAGRUNT_ATLANTIS_CONFIG }}"

      - uses: imranismail/setup-kustomize@v1
      - name: Update the image
        run: |
          pushd argocd/sysapps-sources/overlays/${RELEASE_ENV}/atlantis
          kustomize edit set image ${{ env.REGISTRY }}/${{ env.REPO }}=${{ env.REGISTRY }}/${{ env.REPO }}:${{ steps.release.outputs.tag_name }}
          popd

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          author: ${{ github.actor }} <${{ github.actor }}@github.com>
          commit-message: Release ${{ env.REPO }} image ${{ steps.release.outputs.tag_name }}
          assignees: ${{ github.actor }}
          labels: |
            release
            automated pr
          reviewers: ${{ github.actor }}
          title: Bump ${{ env.REPO }} version ${{ steps.release.outputs.tag_name }}
          body: |
            Update report
            - PR created by ${{ github.actor }}
            - Image version ${{ github.ref_name }}
            - Commits: ${{ github.event.head_commit.message }}
          branch: release-from-${{ env.REPO }}-${{ steps.release.outputs.tag_name }}
          base: main
          path: argocd
          draft: false
          signoff: false    
