name: Relase Atlantis Custom Image

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ATLANTIS: "0.22.3"
  TERRAFORM: "1.3.8"
  TERRAGRUNT: "0.38.9"
  TERRAGRUNT_ATLANTIS_CONFIG: "1.16.0"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
          
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Login to registry ${{ env.REGISTRY_TYPE }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.release.outputs.tag_name }}
          build-args: |
            "ATLANTIS=${{ env.ATLANTIS }}"
            "TERRAFORM=${{ env.TERRAFORM }}"
            "TERRAGRUNT=${{ env.TERRAGRUNT }}"
            "TERRAGRUNT_ATLANTIS_CONFIG=${{ env.TERRAGRUNT_ATLANTIS_CONFIG }}"
          
